<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArusKasSeeder extends Seeder
{
    public function run(): void
    {
        // -------------------------------------------------------
        // arus_kas
        // -------------------------------------------------------
        DB::table('arus_kas')->insert([
            ['id' => 1, 'nama_akun' => 'SALDO KAS SETARA KAS AWAL', 'urutan' => 0, 'sub' => 0, 'super_sub' => 1, 'status' => 'A'],
            ['id' => 2, 'nama_akun' => 'A. PENERIMAAN OPERASI', 'urutan' => 0, 'sub' => 0, 'super_sub' => 2, 'status' => 'A'],
            ['id' => 3, 'nama_akun' => 'Penerimaan Angsuran Pokok Piutang Masyarakat SPP', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 4, 'nama_akun' => 'Penerimaan Jasa Piutang Masyarakat SPP', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 5, 'nama_akun' => 'Penerimaan Denda Piutang Masyarakat SPP', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 6, 'nama_akun' => 'Penerimaan Angsuran Pokok Piutang Masyarakat UEP', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 7, 'nama_akun' => 'Penerimaan Jasa Piutang Masyarakat UEP', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 8, 'nama_akun' => 'Penerimaan Denda Piutang Masyarakat UEP', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 9, 'nama_akun' => 'Penerimaan Angsuran Pokok Piutang Lembaga Lain', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 10, 'nama_akun' => 'Penerimaan Jasa Piutang Lembaga Lain', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 11, 'nama_akun' => 'Penerimaan Denda Piutang Lembaga Lain', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 12, 'nama_akun' => 'Penerimaan Bunga Bank', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 13, 'nama_akun' => 'Penerimaan Pendapatan investasi (dari Anak Usaha)', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 14, 'nama_akun' => 'Penerimaan Lain-lain', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 15, 'nama_akun' => 'Penarikan Rekening Antar Kantor', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 16, 'nama_akun' => 'PENGELUARAN', 'urutan' => 0, 'sub' => 0, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 17, 'nama_akun' => 'B. Pencairan Piutang Masyarakat Dan Rekening Antar', 'urutan' => 0, 'sub' => 0, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 18, 'nama_akun' => 'Pencairan Piutang Masyarakat Kelompok SPP', 'urutan' => 0, 'sub' => 17, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 19, 'nama_akun' => 'Pencairan Piutang Masyarakat Kelompok UEP', 'urutan' => 0, 'sub' => 17, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 20, 'nama_akun' => 'Pencairan Piutang Lembaga Lain', 'urutan' => 0, 'sub' => 17, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 21, 'nama_akun' => 'Penempatan Rekening Antar Kantor', 'urutan' => 0, 'sub' => 17, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 22, 'nama_akun' => 'C. Pengeluaran Operasi', 'urutan' => 0, 'sub' => 0, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 23, 'nama_akun' => 'Bayar Gaji', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 24, 'nama_akun' => 'Bayar Honor', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 25, 'nama_akun' => 'Bayar Tunjangan', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 26, 'nama_akun' => 'Bayar Bonus Prestasi Kerja', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 27, 'nama_akun' => 'Beban Administrasi dan Umum', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 28, 'nama_akun' => 'Beban Listrik dan Air', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 29, 'nama_akun' => 'Beban Internet', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 30, 'nama_akun' => 'Beban Pemeliharaan & Perbaikan Aset', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 31, 'nama_akun' => 'Konsumsi Kantor dan Tamu', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 32, 'nama_akun' => 'Beban Iuran Organisasi', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 33, 'nama_akun' => 'Beban Biaya Audit', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 34, 'nama_akun' => 'Beban Rapat / MAD', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 35, 'nama_akun' => 'Beban Peningkatan Kapasitas', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 36, 'nama_akun' => 'Beban Pembinaan Kelompok', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 37, 'nama_akun' => 'Bayar Transportasi dan Perjalanan Dinas', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 38, 'nama_akun' => 'Bayar Bunga Utang', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 39, 'nama_akun' => 'Bayar Beban Usaha Lainnya', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 40, 'nama_akun' => 'Bayar Beban Pemasaran', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 41, 'nama_akun' => 'Bayar Pajak Bank', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 42, 'nama_akun' => 'Bayar Administrasi Bank', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 44, 'nama_akun' => 'Bayar Kegiatan Sosial dan Masyarakat', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 45, 'nama_akun' => 'Bayar Non Usaha Lainnya', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 46, 'nama_akun' => 'INVESTASI', 'urutan' => 0, 'sub' => 0, 'super_sub' => 3, 'status' => 'A'],
            ['id' => 47, 'nama_akun' => 'A. Penerimaan', 'urutan' => 0, 'sub' => 0, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 48, 'nama_akun' => 'Penarikan Investasi dari Unit Usaha', 'urutan' => 0, 'sub' => 47, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 49, 'nama_akun' => 'Penjualan Aset Tetap dan inventaris', 'urutan' => 0, 'sub' => 47, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 50, 'nama_akun' => 'Penjualan Aset Tak Berwujud', 'urutan' => 0, 'sub' => 47, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 51, 'nama_akun' => 'Perolehan Kas dalam aktivitas Investasi Lainnya', 'urutan' => 0, 'sub' => 47, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 52, 'nama_akun' => 'B. Pengeluaran', 'urutan' => 0, 'sub' => 0, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 53, 'nama_akun' => 'Penempatan Investasi kepada Unit Usaha', 'urutan' => 0, 'sub' => 52, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 54, 'nama_akun' => 'Bayar Pembelian Tanah', 'urutan' => 0, 'sub' => 52, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 55, 'nama_akun' => 'Bayar Pembelian Gedung & Bangunan', 'urutan' => 0, 'sub' => 52, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 56, 'nama_akun' => 'Bayar Pembelian Kendaraan & Mesin', 'urutan' => 0, 'sub' => 52, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 57, 'nama_akun' => 'Bayar Pembelian Inventaris', 'urutan' => 0, 'sub' => 52, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 58, 'nama_akun' => 'Bayar Biaya Pendirian & Perijinan Organisasi', 'urutan' => 0, 'sub' => 52, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 59, 'nama_akun' => 'Bayar Biaya Lisensi', 'urutan' => 0, 'sub' => 52, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 60, 'nama_akun' => 'Bayar Sewa/Biaya Dibayar Dimuka', 'urutan' => 0, 'sub' => 52, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 61, 'nama_akun' => 'PENDANAAN', 'urutan' => 0, 'sub' => 0, 'super_sub' => 4, 'status' => 'A'],
            ['id' => 62, 'nama_akun' => 'A. Penerimaan', 'urutan' => 0, 'sub' => 0, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 63, 'nama_akun' => 'Setoran Modal', 'urutan' => 0, 'sub' => 62, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 64, 'nama_akun' => 'Utang Bank', 'urutan' => 0, 'sub' => 62, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 65, 'nama_akun' => 'Utang Lainnya', 'urutan' => 0, 'sub' => 62, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 66, 'nama_akun' => 'B. Pengeluaran', 'urutan' => 0, 'sub' => 0, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 67, 'nama_akun' => 'Penarikan Dana Penyertaan', 'urutan' => 0, 'sub' => 66, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 68, 'nama_akun' => 'Pembayaran Utang Bank', 'urutan' => 0, 'sub' => 66, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 69, 'nama_akun' => 'Pembayaran Utang Pembagian Laba', 'urutan' => 0, 'sub' => 66, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 70, 'nama_akun' => 'Pembayaran Utang Lainnya', 'urutan' => 0, 'sub' => 66, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 71, 'nama_akun' => 'Bayar Pajak', 'urutan' => 0, 'sub' => 22, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 72, 'nama_akun' => 'Penerimaan Piutang Lain', 'urutan' => 0, 'sub' => 2, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 73, 'nama_akun' => 'Pencairan Piutang Lain', 'urutan' => 0, 'sub' => 17, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 74, 'nama_akun' => 'Penghapusan Piutang', 'urutan' => 0, 'sub' => 17, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 75, 'nama_akun' => 'Bayar Konstruksi dalam Pengerjaan dan Uang Muka', 'urutan' => 0, 'sub' => 52, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 76, 'nama_akun' => 'Perolehan Kas dalam Konstruksi Dalam Pengerjaan/Uang Muka', 'urutan' => 0, 'sub' => 47, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 77, 'nama_akun' => 'Bayar Aset Lain-lain', 'urutan' => 0, 'sub' => 52, 'super_sub' => 0, 'status' => 'A'],
            ['id' => 78, 'nama_akun' => 'Perolehan Kas dalam Aset Lain-lain', 'urutan' => 0, 'sub' => 47, 'super_sub' => 0, 'status' => 'A'],
        ]);

        // -------------------------------------------------------
        // arus_kas_rekening
        // -------------------------------------------------------
        DB::table('arus_kas_rekenings')->insert([
            ['arus_kas_id' => 3, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.1.03.01'],
            ['arus_kas_id' => 4, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.1.03.04'],
            ['arus_kas_id' => 4, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.1.01.01'],
            ['arus_kas_id' => 4, 'rekening_debit' => '1.1.03.04', 'rekening_kredit' => '4.1.01.01'],
            ['arus_kas_id' => 5, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.1.01.04'],
            ['arus_kas_id' => 6, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.1.03.02'],
            ['arus_kas_id' => 7, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.1.03.05'],
            ['arus_kas_id' => 7, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.1.01.02'],
            ['arus_kas_id' => 7, 'rekening_debit' => '1.1.03.05', 'rekening_kredit' => '4.1.01.02'],
            ['arus_kas_id' => 8, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.1.01.05'],
            ['arus_kas_id' => 9, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.1.03.03'],
            ['arus_kas_id' => 10, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.1.03.06'],
            ['arus_kas_id' => 10, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.1.01.03'],
            ['arus_kas_id' => 11, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.1.01.06'],
            ['arus_kas_id' => 12, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.2.01.01'],
            ['arus_kas_id' => 12, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.2.01.02'],
            ['arus_kas_id' => 12, 'rekening_debit' => '1.1.02.01', 'rekening_kredit' => '4.2.01.01'],
            ['arus_kas_id' => 12, 'rekening_debit' => '1.1.02.01', 'rekening_kredit' => '4.2.01.02'],
            ['arus_kas_id' => 13, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.1.02.01'],
            ['arus_kas_id' => 13, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.1.02.02'],
            ['arus_kas_id' => 13, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.1.02.03'],
            ['arus_kas_id' => 14, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.1.02.99%'],
            ['arus_kas_id' => 14, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.2.01.07%'],
            ['arus_kas_id' => 14, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.2.01.06'],
            ['arus_kas_id' => 15, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.1.05%'],
            ['arus_kas_id' => 18, 'rekening_debit' => '1.1.03.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 19, 'rekening_debit' => '1.1.03.02', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 20, 'rekening_debit' => '1.1.03.03', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 21, 'rekening_debit' => '1.1.05%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 23, 'rekening_debit' => '5.1.01.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 23, 'rekening_debit' => '5.1.01.02', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 23, 'rekening_debit' => '2.1.02.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 24, 'rekening_debit' => '5.1.01.03', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 24, 'rekening_debit' => '5.1.01.04', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 24, 'rekening_debit' => '5.1.01.05', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 24, 'rekening_debit' => '5.1.01.06', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 24, 'rekening_debit' => '5.1.01.07', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 24, 'rekening_debit' => '5.1.01.08', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 24, 'rekening_debit' => '2.1.02.02', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 24, 'rekening_debit' => '5.1.01.09', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 25, 'rekening_debit' => '5.1.02.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 25, 'rekening_debit' => '5.1.02.02', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 25, 'rekening_debit' => '5.1.02.03', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 25, 'rekening_debit' => '5.1.02.04', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 25, 'rekening_debit' => '2.1.02.03', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 25, 'rekening_debit' => '5.1.02.06', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 25, 'rekening_debit' => '5.1.02.07', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 26, 'rekening_debit' => '5.1.02.05', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 26, 'rekening_debit' => '2.1.02.04', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 27, 'rekening_debit' => '5.1.03.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 28, 'rekening_debit' => '5.1.03.02', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 28, 'rekening_debit' => '5.1.03.05', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 29, 'rekening_debit' => '5.1.03.03', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 30, 'rekening_debit' => '5.1.03.04', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 31, 'rekening_debit' => '5.1.04.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 32, 'rekening_debit' => '5.1.04.02', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 33, 'rekening_debit' => '5.1.04.03', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 34, 'rekening_debit' => '5.1.05.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 35, 'rekening_debit' => '5.1.05.02', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 36, 'rekening_debit' => '5.1.05.03', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 36, 'rekening_debit' => '5.1.05.04', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 37, 'rekening_debit' => '5.1.06%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 38, 'rekening_debit' => '5.1.08%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 39, 'rekening_debit' => '5.1.09%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 40, 'rekening_debit' => '5.2.01%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 41, 'rekening_debit' => '5.3.01.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 41, 'rekening_debit' => '5.3.01.01', 'rekening_kredit' => '1.1.02%'],
            ['arus_kas_id' => 42, 'rekening_debit' => '5.3.01.02', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 42, 'rekening_debit' => '5.3.01.02', 'rekening_kredit' => '1.1.02%'],
            ['arus_kas_id' => 44, 'rekening_debit' => '5.3.03%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 45, 'rekening_debit' => '5.3.04%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 48, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.1.06%'],
            ['arus_kas_id' => 49, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.2.02%'],
            ['arus_kas_id' => 49, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.2.01.01'],
            ['arus_kas_id' => 49, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.2.01.04'],
            ['arus_kas_id' => 50, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.2.04%'],
            ['arus_kas_id' => 51, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.2.01.03'],
            ['arus_kas_id' => 51, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '4.3.01%'],
            ['arus_kas_id' => 53, 'rekening_debit' => '1.1.06%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 54, 'rekening_debit' => '1.2.01.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 55, 'rekening_debit' => '1.2.01.02', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 56, 'rekening_debit' => '1.2.01.03', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 57, 'rekening_debit' => '1.2.01.04', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 58, 'rekening_debit' => '1.2.03.01%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 59, 'rekening_debit' => '1.2.03.02', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 60, 'rekening_debit' => '1.2.03.03', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 60, 'rekening_debit' => '1.2.03.04', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 63, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '3.1%'],
            ['arus_kas_id' => 64, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '2.1.01%'],
            ['arus_kas_id' => 64, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '2.2.01%'],
            ['arus_kas_id' => 65, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '2.1.05.01'],
            ['arus_kas_id' => 65, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '2.2.02.01'],
            ['arus_kas_id' => 67, 'rekening_debit' => '3.1.01%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 68, 'rekening_debit' => '2.1.01%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 68, 'rekening_debit' => '2.2.01%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 69, 'rekening_debit' => '2.1.04%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 70, 'rekening_debit' => '2.1.02.05', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 70, 'rekening_debit' => '2.1.05.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 70, 'rekening_debit' => '2.2.02.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 71, 'rekening_debit' => '5.4.01.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 71, 'rekening_debit' => '2.1.03.01', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 72, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.1.03.07'],
            ['arus_kas_id' => 72, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.1.03.08'],
            ['arus_kas_id' => 73, 'rekening_debit' => '1.1.03.07', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 73, 'rekening_debit' => '1.1.03.08', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 74, 'rekening_debit' => '1.1.04%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 75, 'rekening_debit' => '1.2.05%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 76, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.2.05%'],
            ['arus_kas_id' => 77, 'rekening_debit' => '1.3.01%', 'rekening_kredit' => '1.1.01%'],
            ['arus_kas_id' => 78, 'rekening_debit' => '1.1.01%', 'rekening_kredit' => '1.3.01%'],
        ]);
    }
}
