version: "3.8"

services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: astamart-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html:z
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:z
        networks:
            - astamart-network
            - web-network

    # Nginx Service
    web:
        image: nginx:alpine
        container_name: astamart-web
        restart: unless-stopped
        ports:
            - "8002:80"
        volumes:
            - .:/var/www/html:z
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:z
        networks:
            - astamart-network
            - web-network
        depends_on:
            - app

    # Redis Service
    redis:
        image: redis:alpine
        container_name: astamart-redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - astamart-network
            - web-network

    # Mailpit Service
    mailpit:
        image: "axllent/mailpit:latest"
        container_name: astamart-mailpit
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - astamart-network
            - web-network

networks:
    astamart-network:
        driver: bridge
    web-network:
        external: true
